### ISSUE TITLE
Very nice board.

### ISSUE THREAD

**Issue by janrinze** [joshtyler/manila-ice#1]
I like this board.
SDRAM + 2x PMOD is really nice.
If you will be having any spares then I am willing to buy one from you.

Great work!
Jan Rinze.

**Comment by joshtyler** [comment]
Hi Jan,

Thank you, I'm glad you like it. I'm impressed that you found the board given that I haven't got around to uploading any documentation yet!

I've had a few boards manufactured and am now testing them.
![DSC08552](https://user-images.githubusercontent.com/7274318/70005399-6ba1d380-1561-11ea-8705-4f8a3c141b47.jpg)

I wanted to try out whether it was possible to get any reasonable gigabit ethernet performance with an iCE40 FPGA, so I put together this credit card sized dev board. It has a GE Phy, SDRAM, 2 PMODs, a reasonable size QSPI flash, and a USB UART. There are also a couple of switches, 8 debug LEDs, and an EEPROM to store things like serial numbers and MAC addresses.

So far I've tested that the power rails come up, that FPGA can configure itself and blink the LEDs, the USB UART, and that the PHY is able to negotiate to 1000BASE-T.

I'm just writing a small bootloader to take in a configuration image over the UART interface and save it into flash, then it should be usable as a standalone unit.

Once I've gotten this done, and tested the other interfaces, I'll let you know, as I should have a few spare boards. Progress might be a bit slow though, as I'm just working on this in a bit of my spare time!

**Comment by janrinze** [comment]
Hi, it's been a while.
How is it going with the board?

**Comment by joshtyler** [comment]
Hi Jan,

I've got the serial bootloader working, so I can now upload code to the board without a separate programming cable - I've just got to test the various peripherals and interfaces now.

**Comment by joshtyler** [comment]
Hi Jan,

Sorry for not getting back to you, this Issue completely slipped my mind! I do have a few spare boards. Happy to sell one to you.

Give me an email at josh.tyler@btinternet.com if you are still interested and we can discuss :smile: 

Josh
